### ISSUE TITLE
BUGS

### ISSUE THREAD

**Issue by annagabain** [annagabain/mom-network-frontend#23]
- [ ] Conditional rendering: 
- [ ] register page should work similar to login page and hide the navbar
- [ ] 

- [ ] 

> footer positioning, especially for mobile

**Comment by ElReyUno** [comment]
Where is the code repo? What Tool Stack (language(s) and framework(s)) are you looking to use? 

With nothing else to go off of here is a high-level explanation of each requirement:

1. Conditional Rendering for Register Page:
   - To make the register page work similarly to the login page and hide the navbar, you could use conditional rendering. Ensure that the navbar is not displayed when the user is on the register page.
   - This can typically be achieved by using conditional statements in your frontend code (e.g., JavaScript, React, Angular, or Vue.js) to control the visibility of the navbar based on the current route or page.

1. Fixed Header and Footer:
   - To implement a fixed header and footer, you could use CSS to set the position property to fixed for both the header and footer elements.
   - For example, in CSS, you could do something like this (customize the styling (colors, heights, etc.) to match your design):

``` css
header {
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  background-color: #333; /* Adjust as needed */
  z-index: 100; /* Ensure it's above other content */
}

footer {
  position: fixed;
  bottom: 0;
  left: 0;
  width: 100%;
  background-color: #333; /* Adjust as needed */
  z-index: 100; /* Ensure it's above other content */
}
```

3. Mobile-Related Functionality:
   - To make sure the user stays logged in until they decide otherwise implement user authentication with a mechanism for a persisting login state. You could use technologies like cookies or local storage to achieve this.
   - To troubleshoot the "create new post" button issue provide more context or error messages to pinpoint the problem. Common issues include JavaScript errors, API calls not working, or incorrect routing.
   - Footer positioning for mobile could be adjusted by using CSS media queries to style the footer differently for smaller screens. For example:

``` css
@media (max-width: 768px) {
  footer {
    /* Your mobile-specific styles here */
  }
}
```

I hope that helps.  If not please provide more feedback. 

The pseudo-code above should get you started however you will have to modify for your specific requirements.

Good Luck!
